[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unic-ucd-category = "0.9.0"
strum = { version = "0.23", features = ["derive"] }
