[package]
name = "mlang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser = {path = "../../parser"}
compiler = {path = "../../compiler"}
clap = "4.0.15"
goldentests = "1.1.1"

